services:
  app1:
    build: .
    ports:
      - "8000:8080"
    environment:
      SERVER_NAME: "server 1"

  app2:
    build: .
    ports:
      - "8050:8080"
    environment:
      SERVER_NAME: "server 2"

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
